version: '3.5'

services:
  postgres:
    container_name: exam_postgres
    image: postgres:12.12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_DB: exam
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "6432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  local_network:
    attachable: true

volumes:
  postgres: